name: Collect

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '0 3 * * *'
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  collect:
    name: Collect code metrics using octocov central mode
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: 967671
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Check out source code
        uses: actions/checkout@v4
      - name: Run octocov
        uses: k1LoW/octocov-action@v1
        with:
          github-token: ${{ steps.app-token.outputs.token }}
