name: Collect

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '0 3 * * *'
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  collect:
    name: Collect code metrics using octocov central mode
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
      - name: Run octocov
        uses: k1LoW/octocov-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
